---
title: "Explore Rainfall & Trigger"
output:
    flexdashboard::flex_dashboard:
            orientation: rows
date: "2023-05-03"
runtime: shiny
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = F,messages=F)
options(tidyverse.quiet = TRUE,
        here.quiet=TRUE,
        lubridate.quiet=TRUE
        )
```

```{r, include=F}
library(tidyverse)
library(lubridate)
library(glue)
# library(sf)
# library(leaflet)
# library(targets)
library(sysfonts)
library(gghdx)
library(glue)
library(here)
# library(zoo)
library(extRemes)
library(shiny)
# library(flexdashboard)
# library(data.table)
# tar_source()

source(here::here("R/tar_return_periods.R"))

font_add_google("Source Sans Pro")
showtext::showtext_auto()
# tar_load(hres_rolled_per_date_gen)

hres_forecast <- read_rds(here::here("shinydata/hres_rolled_per_date_gen.rds"))
era_chirps <- read_rds(here::here("shinydata/era_chirps_long.rds"))
chirps_gefs_forecast <- read_rds(here::here("shinydata/chirps_gefs.rds"))



    

```


```{r test, echo=FALSE, out.width="100%"}

forecast_filt <- reactive({
    hres_forecast %>%
    filter(name == input$cumulation_window,
           date_forecast_made==as_date(input$date),
           governorate_name==input$gov) %>%
    mutate(
        activation = case_when(
            value>=input$thresh & leadtime %in% c(1:5)~ "Action",
            value>=input$thresh & leadtime %in% c(6:10)~ "Readiness",
            value<input$thresh ~ "No Activation",
        ) %>% 
            fct_expand("Action","Readiness","No Activation")
    )})

forecast_filt2 <- reactive({
    hres_forecast %>%
    filter(name == input$cumulation_window2,
           governorate_name==input$gov2) %>%
    mutate(
        activation = case_when(
            value>=input$thresh2 & leadtime %in% c(1:5)~ "Action",
            value>=input$thresh2 & leadtime %in% c(6:10)~ "Readiness",
            value<input$thresh2 ~ "No Activation",
        ) %>% 
            fct_expand("Action","Readiness","No Activation")
    )})


plot_title_text <- reactive({
    df <- forecast_filt() %>% 
        filter(!is.na(activation))
    if(all(df$activation=="No Activation")){
     ret <- "No activation"   
    }
    if(any(df$activation=="Action")){
        
        action_df <- df %>% 
            filter(
                activation == "Action"
            ) %>% 
            slice(1)
     
        
        ret <- glue("Action Phase Triggered on {input$date} due to expected {convert_window_numeric_r()} day rainfall on {action_df$date_forecast_predict}")
    }
    if(nrow(df %>% filter(activation=="Action"))==0 & any(df$activation=="Readiness")){
     readiness_df <- df %>% 
            filter(
                activation == "Readiness"
            ) %>% 
            slice(1)
       ret <-  glue("Readiness Phase Triggered on {input$date} due to expected {convert_window_numeric_r()} day rainfall on {readiness_df$date_forecast_predict}")
    }
    return(ret)
    
        
})

gen_theme <-  function(title_length){
    if (title_length < 30) {
  my_theme <- theme(
      plot.title = element_text(margin = margin(b = 10), size = 16))
} else if (title_length < 60) {
  my_theme <- theme(plot.title = element_text(margin = margin(b = 15), size = 14))
} else {
  my_theme <- theme(plot.title = element_text(margin = margin(b = 20), size = 12))
}
    return(my_theme)
}


theme_dynamic <- reactive({
    gen_theme(title_length = nchar(plot_title_text()))
})


convert_window_numeric <- function(x){
         switch(x,
           "precip_daily" = "1 ",
           "roll3"= "3 ",
           "roll5" = "5 ",
           "roll10"="10") 
}
convert_window_numeric_r <- reactive({
    convert_window_numeric(input$cumulation_window)
})




y_axis_label <-  reactive({
    convert_window_numeric(input$cumulation_window) %>%
        paste0("Rainfall Accumulation (mm)")}
    )

readiness_dates <- reactive({
    forecast_filt() %>% 
        filter(leadtime %in% c(6:10)) %>% 
        pull(date_forecast_predict)
})
action_dates <- reactive({
    forecast_filt() %>% 
        filter(leadtime %in% c(1:5)) %>% 
        pull(date_forecast_predict)
})

alert_phase_lines_y_pos <- reactive({
    max_forecase_pos_val<- max(forecast_filt()$value,na.rm=T)*1.1
    thresh_pos_val<- input$thresh*1.1
    max(max_forecase_pos_val,thresh_pos_val)
    
})
```

Realtime Simulation {data-orientation=columns}
=====================================  
    
```{r page1UI, echo=FALSE}

fluidRow( 
         column(width=3,
                dateInput(inputId="date",label = "Date",value = "2022-07-13")
                ),
         column(width=3,
                selectInput(inputId="cumu_window",choices = c("Daily"="precip_daily",
                                                    "3 Day"="roll3",
                                                    "5 Day"="roll5",
                                                    "10 Day"= "roll10"),label = "Rainfall accumulation",selected = "roll3")),
         # column(width=3,
         #        selectInput(inputId="gov",choices = c("Hajjah","Marib"),label = "Governorate",selected = "Hajjah")),
         column(width=3,
                numericInput(inputId = "thresh",label = "Threshold",value = 19.8,min = 0,step = 0.1))
)
```

Column {data-width=650}
-------------------------------------

```{r page1Plot, echo=FALSE}
renderPlot({
    
    forecast_filt <- hres_forecast %>%
        filter(name == input$cumu_window,
               date_forecast_made==as_date(input$date)) %>%
        mutate(
            activation = case_when(
                value>=input$thresh & leadtime %in% c(1:5)~ "Action",
                value>=input$thresh & leadtime %in% c(6:10)~ "Readiness",
                value<input$thresh ~ "No Activation",
            ) %>% 
                fct_expand("Action","Readiness","No Activation"),
            txt_label=glue("{activation} predicted {format(date_forecast_predict,'%m-%d')} ({leadtime})")
        )
    y_axis_label <- convert_window_numeric(input$cumu_window) %>%
        paste0("Rainfall Accumulation (mm)")
    
    readiness_dates <-  forecast_filt %>% 
        filter(leadtime %in% c(6:10)) %>% 
        pull(date_forecast_predict) %>% 
        unique()
    
    action_dates <-  forecast_filt %>% 
        filter(leadtime %in% c(1:5)) %>% 
        pull(date_forecast_predict) %>% 
        unique()
    # top_plot<- max(max(forecast_filt()$value,na.rm = T),input$thresh)+10
            
    p <- forecast_filt %>% 
        ggplot(aes(x=date_forecast_predict,y=value))+
        geom_point(aes(color=activation, group=activation, size=activation))+
        geom_text(data=forecast_filt %>% 
                      filter(value>=input$thresh),aes(x= date_forecast_predict,y= value+10,color=activation, group=activation,label=txt_label))+
        scale_size_manual(values = c("Action"=8,"No Activation"=1,"Readiness"=8),na.translate=F,guide="none")+
        scale_color_manual(values = c("Action"="red","No Activation"="black","Readiness"="orange"),na.translate=F,drop=F)+
        geom_line()+
        geom_hline(yintercept = input$thresh)+
        scale_x_date(breaks = "1 day",date_labels = "%m-%d")+
        # scale_y_continuous(limits = c(-2,top_plot),breaks = seq(0,100,10))+
        labs(y=y_axis_label
             # title  = plot_title_text(),
             )+
        geom_segment( x=readiness_dates[1],xend=readiness_dates[5],y=-1, yend = -1,alpha=0.2,color="orange")+
        geom_segment( x=action_dates[1],xend=action_dates[5],y=-1 ,yend = -1,alpha=0.2,color="red")+
        annotate("text",x = median(readiness_dates),y = -2,label="readiness phase",color="orange")+
        annotate("text",x = median(action_dates),y = -2,label="action phase",color="red")+
        facet_wrap(~governorate_name,nrow = 2,ncol=1)+
        theme_hdx()+
        # theme_dynamic()+
        theme(
            axis.text.x = element_text(angle=90),
            panel.border = element_rect(fill = NA, 
            colour = "grey20")
        )
    return(p)

}, height =1000)



```

Column {data-width=350}
-------------------------------------

```{r}

renderDataTable({
    era_chirps_tfilt <-  era_chirps %>% 
        filter(year(date)>=1981) %>% 
        mutate(
            splitter= glue("{source}_{governorate_name}_{precip_regime}")
        ) 
    
    
    tables_split <- era_chirps_tfilt %>% 
        split(.$splitter) %>% 
        imap_dfr(\(df_temp,nm){
            return_period_level_tibble(df = df_temp,
                                       value = "value",
                                       date = "date",
                                       rp_year = c(2,3,4,5 )) %>% 
                mutate(tbl_name=nm)
            
        })
    
    
    tables_merged <- tables_split %>% 
        mutate(
            governorate_name= str_extract(tbl_name,"Hajjah|Marib"),
            source = str_extract(tbl_name,"CHIRPS|ERA"),
            precip_regime = str_extract(tbl_name,"precip.*|roll.*"),
            
        ) %>% 
        select(RP, governorate_name,precip_regime, source, RP_level=estimate) %>% 
        pivot_wider(names_from = governorate_name,values_from = RP_level)
    
    tables_merged %>% 
        filter(precip_regime==input$cumu_window)
    
})


```


Triggers & Historical {data-orientation=rows}
=====================================
   

```{r historicalUI, echo=FALSE, out.width="100%", height="500px"}
fluidRow(
         column(width=2,
                selectInput(inputId="cum_window3",choices = c("Daily"="precip_daily",
                                                    "3 Day"="roll3",
                                                    "5 Day"="roll5",
                                                    "10 Day"= "roll10"),label = "Rainfall accumulation",selected = "roll3")),
         column(width=2,
                numericInput(inputId = "thresh3",label = "Threshold",value = 19.8,min = 0,step = 0.1)
                ),
         column(width=2,
                dateRangeInput("daterange", "Date range:",
                 start  = as_date("2021-01-01"),
                 end    = as_date("2021-12-31"),
                 min    = as_date("1981-01-01"),
                 max    = as_date("2022-12-31"),
                 format ="yyyy-mm-dd"
                 )),
         column(width=2,
                selectInput(inputId="forecast_type",label="Forecast:",choices=c("ECMWF - HRES"="hres","CHIRPS-GEFS"="chirps_gefs"),selected="hres")
         ),
         column(width=4,
                selectInput(inputId="trig_freq",label="Trigger can be activaed 1x per (not functional)",choices=c("Season"="season","10 Days","30 Days"),selected="season")
         )
         
)
```


Row {data-height=1000}
-------------------------------------
```{r historicalPlot,echo=F}

renderPlot({
    y_axis_tite <- convert_window_numeric(input$cum_window3) %>% 
        paste0(" Day Accumulation (mm)")
    
    # rm_leads <- seq(0,(roll_number-1))
    start_date <-as.character(input$daterange[1])
    end_date <-as.character(input$daterange[2])
    
    chirps_gefs_tfilt <- chirps_gefs_forecast %>% 
            filter(date_forecast_predict >=start_date,
                   date_forecast_predict<=end_date)
    
    hres_forecast_tfilt <- hres_forecast %>% 
            filter(date_forecast_predict >=start_date,
                   date_forecast_predict<=end_date)
    
    y_top_limit<- max(max(chirps_gefs_tfilt$value,na.rm=T),max(hres_forecast_tfilt$value,na.rm=T))+10
    
    
    if(input$forecast_type=="hres"){
        forecast <- hres_forecast_tfilt
            
           ribbon_color <- "#c2e699"
        
    }
    if(input$forecast_type=="chirps_gefs"){
        forecast <- chirps_gefs_tfilt
        ribbon_color <- "#41b6c4"
     
    }
    forecast_filt_temp <- forecast %>% 
        filter(name==input$cum_window3) %>% 
        mutate(
            season = case_when(
                month(date_forecast_predict) %in% c(3,4,5,6) ~ "March-April-May-June",
                month(date_forecast_predict) %in% c(7,8,9,10) ~ "July-August-September-October",
                TRUE~"dry season"
            ),
            trigger_window = case_when(
                leadtime %in% c(1:5)~ "action window",
                leadtime %in% c(6:10)~ "readiness window"
            ) 
        )

    forecast_filt_ribbon_df <- forecast_filt_temp %>% 
      group_by(governorate_name,date_forecast_predict,.drop=F) %>% 
    summarise(
        min_val= min(value,na.rm=T),
        max_val = max(value,na.rm=T),.groups="drop"
    ) %>% 
    mutate(
        min_val = ifelse(is.infinite(min_val),NA,min_val),
        max_val = ifelse(is.infinite(max_val),NA,max_val)
    )
    

    
    max_vals_per_window_phase <- forecast_filt_temp %>%
        filter(value >=input$thresh3) %>% 
        group_by(governorate_name,year=year(date_forecast_predict),season, trigger_window) %>% 
        filter(date_forecast_made==min(date_forecast_made),leadtime==max(leadtime)) %>% 
        arrange(season, trigger_window) %>% 
        ungroup() %>% 
        mutate(
            txt_label = glue("{str_remove(trigger_window,' window')} alert on {format(date_forecast_made,'%m-%d')}\ndue to {round(value,1)} mm rainfall predicted on {format(date_forecast_predict,'%m-%d')}"),
            txt_label = glue("predicted {format(date_forecast_made,'%m-%d')} ({leadtime})"),
            txt_label_x = if_else(trigger_window=="action window",date_forecast_predict+10,date_forecast_predict-10)
        )
    
    p <- era_chirps %>% 
        filter(date >=start_date,date<=end_date) %>% 
        filter(precip_regime==input$cum_window3) %>% 
        ggplot()+
        geom_ribbon(data= forecast_filt_ribbon_df,
                    aes(date_forecast_predict,ymin=min_val, ymax=max_val),fill=ribbon_color,alpha=0.7)+
        geom_hline(yintercept = input$thresh3,color="red", linetype="dashed")+
        geom_line(aes(x= date, y= value, color=source, group=source),alpha=1,size=1)+
        
        # scale_color_manual(values = c("CHIRPS"="#253494","ERA"="#d95f0e"))
        geom_point(data=max_vals_per_window_phase,aes(x=date_forecast_predict,y=value,color=trigger_window),alpha=0.9,size=5)+
        scale_color_manual(values = c("CHIRPS"="#253494","ERA"="#31a354","action window"="red","readiness window"="orange"),drop=F)+
        geom_text(data=max_vals_per_window_phase,
                  aes(x=txt_label_x,y=50,
                      color=trigger_window, 
                      label = txt_label),angle=90)+
        scale_x_date(date_breaks="1 month",date_minor_breaks = "10 days",date_labels = "%y-%m-%d")+
        scale_y_continuous(limits=c(0,y_top_limit))+
        labs(y=y_axis_tite)+
        facet_wrap(~governorate_name,nrow = 2,ncol=1)+
        theme_hdx()+
        theme(
            axis.title.x = element_blank()
        )
    p
    
}
,height=1000
)

# ggiraph::renderGirafe()
```

<!-- Row {data-height=1000} -->
<!-- ------------------------------------- -->
```{r, eval=F}
renderDataTable({
    start_date <-as.character(input$daterange[1])
    end_date <-as.character(input$daterange[2])
    
    chirps_gefs_tfilt <- chirps_gefs_forecast %>% 
        filter(date_forecast_predict >=start_date,
               date_forecast_predict<=end_date)
    
    hres_forecast_tfilt <- hres_forecast %>% 
        filter(date_forecast_predict >=start_date,
               date_forecast_predict<=end_date)
    
    y_top_limit<- max(max(chirps_gefs_tfilt$value,na.rm=T),max(hres_forecast_tfilt$value,na.rm=T))+10
    
    
    if(input$forecast_type=="hres"){
        forecast <- hres_forecast_tfilt
        ribbon_color <- "#c2e699"
            
    }
    if(input$forecast_type=="chirps_gefs"){
        forecast <- chirps_gefs_tfilt
        ribbon_color <- "#41b6c4"
            
    }
    forecast_filt_temp <- forecast %>% 
        filter(name==input$cum_window3) %>% 
        mutate(
            season = case_when(
                month(date_forecast_predict) %in% c(3,4,5,6) ~ "March-April-May-June",
                month(date_forecast_predict) %in% c(7,8,9,10) ~ "July-August-September-October",
                TRUE~"dry season"
            ),
            trigger_window = case_when(
                leadtime %in% c(1:5)~ "action window",
                leadtime %in% c(6:10)~ "readiness window"
            ) 
        )
    
    # hres_filt_temp <- hres_forecast %>% 
    #     filter(date_forecast_predict >=start_date,date_forecast_predict<=end_date) %>% 
    #     filter(name==input$cum_window3) %>% 
    #     mutate(
    #         season = case_when(
    #             month(date_forecast_predict) %in% c(3,4,5,6) ~ "March-April-May-June",
    #             month(date_forecast_predict) %in% c(7,8,9,10) ~ "July-August-September-October",
    #             TRUE~"dry season"
    #         ),
    #         trigger_window = case_when(
    #             leadtime %in% c(1:5)~ "action window",
    #             leadtime %in% c(6:10)~ "readiness window"
    #         ) 
    #     )
    max_vals_per_window_phase <- forecast_filt_temp %>%
        filter(value >=input$thresh3) %>% 
        group_by(year=year(date_forecast_predict),season, trigger_window) %>% 
        filter(date_forecast_made==min(date_forecast_made),leadtime==max(leadtime)) %>% 
        arrange(season, trigger_window) %>% 
        ungroup() %>% 
        mutate(
            txt_label = glue("{str_remove(trigger_window,' window')} alert on {format(date_forecast_made,'%m-%d')}\ndue to {round(value,1)} mm rainfall predicted on {format(date_forecast_predict,'%m-%d')}"),
            txt_label = glue("predicted {format(date_forecast_made,'%m-%d')} ({leadtime})"),
            txt_label_x = if_else(trigger_window=="action window",date_forecast_predict+10,date_forecast_predict-10)
        )
    max_vals_per_window_phase
})


```




```{r asdf, eval = F}
# non-reactive testing


era_chirps_tfilt <-  era_chirps %>% 
    filter(year(date)>=1981) %>% 
     mutate(
        splitter= glue("{source}_{governorate_name}_{precip_regime}")
    ) 


era_chirps_tfilt %>% 
    split(.$splitter) %>% 
    map(\(df_temp){
           return_period_level_tibble(df = df_temp,
                                                       value = "value",
                                                       date = "date",
                                                       rp_year = c(2,3,4,5 ))
        
    })

era_chirps_tfilt %>% 
    mutate(
        value=ifelse(is.nan(value),NA,value)
    ) %>% 
    split(.$source) %>% 
    map(
        \(df_source){
            df_source %>% 
                split(.$governorate_name) %>% 
                map(\(df_source_gov){
                    df_source_gov
                    split(.$precip_regime) %>% 
                        map(\(df_source_regime){
                            return_period_level_tibble(df = df_source_regime,
                                                       value = "value",
                                                       date = "date",
                                                       rp_year = c(2,3,4,5 )
                            )
                        }
                        )
                }
                )
        }
    )

era_return_periods_df <- chirps_era_wide %>% 
    split(.$governorate_name) %>% 
    imap_dfr(
        \(df_temp,nm){
            c("era_precip_daily","era_roll3","era_roll5","era_roll10") %>% 
                map(\(precip_temp){
                    return_period_level_tibble(df = df_temp,
                           value = precip_temp,
                           date = "date",rp_year = c(2,3,4,5 )) %>% 
                        mutate(precip_regime= precip_temp,
                               governorate_name=nm)
                }
                ) 
            
        }
    ) 
```


```{r, eval=F}

# non-reactive testing
tar_load(era_chirps_long)
thresh_temp
hres_filt_temp <- hres_forecast %>% 
    filter(year(date_forecast_predict)==2021) %>% 
    filter(governorate_name=="Hajjah",name=="roll3") %>% 
    mutate(
        season = case_when(
            month(date_forecast_predict) %in% c(3,4,5,6) ~ "March-April-May-June",
            month(date_forecast_predict) %in% c(7,8,9,10) ~ "July-August-September-October",
            TRUE~"dry season"
        ),
        trigger_window = case_when(
             leadtime %in% c(1:5)~ "action window",
            leadtime %in% c(6:10)~ "readiness window"
        ) 
    ) 
hres_filt_ribbon_df <- hres_filt_temp %>% 
    group_by(date_forecast_predict) %>% 
    summarise(
        min_val= min(value,na.rm=T),
        max_val = max(value,na.rm=T)
    )
max_vals_per_window_phase <- hres_filt_temp %>%
    # filter(year(date_forecast_predict)==2021) %>% 
    filter(value >=thresh_temp) %>% 
    group_by(year=year(date_forecast_predict),season, trigger_window) %>% 
    # filter(leadtime==max(leadtime)) %>% 
    filter(date_forecast_made==min(date_forecast_made),leadtime==max(leadtime)) %>% 
    arrange(season, trigger_window) %>% 
    ungroup() %>% 
    mutate(
        txt_label = glue("{str_remove(trigger_window,' window')} alert on {format(date_forecast_made,'%m-%d')}\ndue to {round(value,1)} mm rainfall predicted on {format(date_forecast_predict,'%m-%d')}"),
        txt_label = glue("predicted {format(date_forecast_made,'%m-%d')} ({leadtime})"),
        txt_label_x = if_else(trigger_window=="action window",date_forecast_predict+10,date_forecast_predict-10)
    )


library(glue)

era_chirps %>% 
    filter(year(date)==2021) %>% 
    filter(precip_regime=="roll3",
           governorate_name=="Hajjah") %>% 
    ggplot()+
    geom_ribbon(data= hres_filt_ribbon_df,aes(date_forecast_predict,ymin=min_val, ymax=max_val))+
    # geom_vline(data=max_vals_per_window_phase,aes(xintercept=date_forecast_made,color=trigger_window),alpha=0.4)+
    geom_point(data=max_vals_per_window_phase,aes(x=date_forecast_predict,y=value,color=trigger_window),alpha=0.4,size=5)+
    # ggrepel::geom_text_repel(data=max_vals_per_window_phase,
    #                           aes(x=date_forecast_predict,y=50,
    #                               color=trigger_window, 
    #                               label = txt_label),angle=90,segment.curvature=0.5)+
    geom_text(data=max_vals_per_window_phase,
                              aes(x=txt_label_x,y=50,
                                  color=trigger_window, 
                                  label = txt_label),angle=90)+
    geom_line(aes(x= date, y= value, color=source, group=source),alpha=0.6)+

    
    # geom_text(data=max_vals_per_window_phase %>% 
    #               filter(trigger_window=="readiness window"),
    #           aes(x= date_forecast_made-10,
    #               y=0,
    #               color =trigger_window,
    #               label=txt_label),hjust="bottom",angle=90)+
    # geom_text(data=max_vals_per_window_phase %>% 
    #               filter(trigger_window=="action window"),
    #           aes(x= date_forecast_made+10,
    #               y=0,
    #               color =trigger_window,
    #               label=txt_label),hjust="bottom",angle=90)+
    theme_hdx()

```


```{r,eval=F}

chirps_gefs_long %>% 
    group_by(governorate_name,date_forecast_predict,.drop=F) %>% 
    summarise(
        min_val= min(value,na.rm=T),
        max_val = max(value,na.rm=T),.groups="drop"
    ) %>% 
    mutate(
        min_val = ifelse(is.infinite(min_val),NA,min_val),
        max_val = ifelse(is.infinite(max_val),NA,max_val)
    )



library(tidyverse)
thresh_temp <- 19.8
hres_filt_temp <- hres_forecast %>% 
    filter(year(date_forecast_predict)>=2017) %>% 
    filter(governorate_name=="Hajjah",name=="roll3") %>% 
    mutate(
        season = case_when(
            month(date_forecast_predict) %in% c(3,4,5,6) ~ "March-April-May-June",
            month(date_forecast_predict) %in% c(7,8,9,10) ~ "July-August-September-October",
            TRUE~"dry season"
        ),
        trigger_window = case_when(
             leadtime %in% c(1:5)~ "action window",
            leadtime %in% c(6:10)~ "readiness window"
        ) 
    ) 

max_vals_per_window_phase <- hres_filt_temp %>% 
    filter(year(date_forecast_predict)==2021) %>% 
    filter(value >=thresh_temp) %>% 
    group_by(date_forecast_predict,trigger_window) %>% 
    filter(leadtime==max(leadtime))

max_vals_per_window_phase <- hres_filt_temp %>% 
    filter(year(date_forecast_predict)==2021) %>% 
    filter(value >=thresh_temp) %>% 
    group_by(season,trigger_window) %>% 
    filter(
        date_forecast_predict==min(date_forecast_predict)
    ) %>% 
    # filter(leadtime==min(leadtime)) %>% 
    arrange(season,trigger_window)
    filter(date_forecast_predict==min(date_forecast_predict),
           leadtime==min(leadtime))
    group_by(date_forecast_predict,trigger_window) %>% 
    filter(leadtime==max(leadtime))

hres_filt_temp %>% 
    filter(year(date_forecast_predict)==2021) %>% 
    group_by(date_forecast_predict,trigger_window) %>% 
    filter(value ==max(value,na.rm=T)) %>% 
    arrange(trigger_window) %>% 
     ggplot(aes(x= date_forecast_predict,y=value, color = trigger_window, group=trigger_window))+
    geom_line(alpha=0.4)+
    geom_segment(data= max_vals_per_window_phase,
                 aes(x=date_forecast_made,
                     xend=date_forecast_predict,
                     y= value,
                     yend=value, color=trigger_window))+
    geom_point(data= max_vals_per_window_phase,
                 aes(x=date_forecast_predict,
                     
                     y= value,
                     color=trigger_window))+
    theme_hdx()



tigger_per <- "season"
hres_filt_temp %>% 
    ggplot(aes(x= date_forecast_predict,y=value))+
    geom_line()+
    geom_point(data=hres_filt_temp %>% 
                   filter(value>=thresh_temp) %>% 
                   mutate(activation = ifelse(leadtime %in% 1:5,"Activation","Warning")) ,
               aes(x= date_forecast_predict, y= value, color=activation)
               
               ) +
    facet_wrap(~leadtime)


hres_gte_thresh_max_lead <- hres_filt_temp %>% 
    mutate(activation = ifelse(leadtime %in% 1:5,"Activation","Warning")) %>%  
    group_by(activation,date_forecast_predict) %>% 
    filter(value>=thresh_temp) %>% 
    arrange(activation,date_forecast_predict,leadtime) %>% 
    filter( leadtime==max(leadtime)) %>%
    ungroup()
hres_gte_thresh_max_lead %>% 
    print(n=30)

hres_filt_temp %>% 
    # filter(leadtime==5) %>% 
    ggplot(aes(x= date_forecast_predict,y=value))+
    geom_line()+
    geom_point(data=hres_gte_thresh_max_lead ,
               aes(x= date_forecast_predict, y= value, color=activation)
               
               ) +
    facet_grid(rows = vars(leadtime))

hres_filt_temp %>% 
    mutate(
        season = case_when(
            month(date_forecast_predict) %in% c(3,4,5,6) ~ "March-April-May-June",
            month(date_forecast_predict) %in% c(7,8,9,10) ~ "July-August-September-October"
        )
    ) %>% 
    filter(month(date_forecast_predict) %in% c(3:10))
```


