# This workflow uses actions to automatically run the global monitoring
# script.

name: yem-trigger-monitoring # changed this from -global monitoring

on:
  workflow_dispatch:
  schedule:
##*1    - cron: "0 11 * * 1-5" # will have to change this to daily
    - cron:"0 2 * * *" # 2

jobs:
  monitor:
    runs-on: macos-latest
##*2    env: 
##*3      RENV_PATHS_ROOT: ~/Library/Caches/org.R-project.R/R/renv # should get rid of this

    steps:
      - uses: actions/checkout@v3
      - name: Set up R 4.2.3
        uses: r-lib/actions/setup-r@f57f1301a053485946083d7a45022b278929a78a
        with:
          r-version: 4.2.3
##*4      - uses: r-lib/actions/setup-pandoc@v2
##*5      - name: Cache packages
##*6        uses: actions/cache@v3
##*7        with:
##*8          path: ${{ env.RENV_PATHS_ROOT }} # should remove - do i need to replace?
##*9          key: ${{ runner.os }}-renv-${{ hashFiles('**/renv.lock') }} # should remove do i need to replace?
##*10          restore-keys: | # should remove do i need to replace?
##*11            ${{ runner.os }}-renv-  # should remove do i need to replace?
##*12      - name: Restore packages
##*13      # can remove `run` section? Rather just source one script which sources another to install req packages?
##*14        run: |
##*15          if (!requireNamespace("renv", quietly = TRUE)) install.packages("renv")
##*16          renv::restore()
##*17        shell: Rscript {0} # not sure if this is required now and also forgot what it does.
      - name: install required packages #18
        run: | #19
          source(file.path("src", "install_req_packages.R")) #20
        shell: Rscript {0} #21
      - name: Create authorization JSON
        id: create-json
        uses: jsdaniell/create-json@v1.2.2
        with:
          name: "auth.json" # this is the name i want `create-json@v1.2.2` to generate right?
          json: ${{ secrets.GCP_CREDENTIALS }}
      - name: Run yem-trigger-monitoring # changed from: Run global monitoring
        run: |
          source(file.path("src", "run.R")) # I'll create "src/run.R" which can source the package install and trigger monitoring.
        shell: Rscript {0} # dont get this really
        env:
          # IDMC_API: ${{ secrets.IDMC_API }} # dont need
          # IPC_API_KEY: ${{ secrets.IPC_API_KEY }} # dont need
          # OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }} # dont need
          YEM_TRIG_MONITORNG: "auth.json" #change name from: `GLOBAL_MONITORING_JSON`, but forget where that name must link to
          CHD_DS_EMAIL_USERNAME: ${{ secrets.CHD_DS_EMAIL_USERNAME }} # this is a key for emails right?
          CHD_DS_EMAIL_PASSWORD: ${{ secrets.CHD_DS_EMAIL_PASSWORD }} # this is a key for emails right?
          CHD_DS_HOST: ${{ secrets.CHD_DS_HOST }} # forgot what this is for
          CHD_DS_PORT: ${{ secrets.CHD_DS_PORT }} # forgot what this is for