# This workflow uses actions to automatically run the aa-yemen-flooding trigger monitoring.
# script.

name: yem-trigger-monitoring

on:
  workflow_dispatch:
  schedule:
    - cron: '25 12 * * *'
        
jobs:
  monitor:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up R 4.2.0
        uses: r-lib/actions/setup-r@f57f1301a053485946083d7a45022b278929a78a
        with:
          r-version: 4.2.0
      - name: install required packages
        run: |
          source(file.path("src", "install_req_r_packages.R"))
        shell: Rscript {0}
      - name: Create authorization JSON
        id: create-json
        uses: jsdaniell/create-json@v1.2.2
        with:
          name: "auth.json" 
          json: ${{ secrets.GCP_CREDENTIALS }}
      - name: Run yem-trigger-monitoring 
        run: |
          source(file.path("src", "update_trigger.R")) 
        shell: Rscript {0} 
        env:
          YEM_TRIG_MONITORNG_JSON: "auth.json" 
          CHD_DS_EMAIL_USERNAME: ${{ secrets.CHD_DS_EMAIL_USERNAME }} 
          CHD_DS_EMAIL_PASSWORD: ${{ secrets.CHD_DS_EMAIL_PASSWORD }} 
          CHD_DS_HOST: ${{ secrets.CHD_DS_HOST }} 
          CHD_DS_PORT: ${{ secrets.CHD_DS_PORT }} 